// SPDX-License-Identifier: LicenseRef-VPL WITH AGPL-3.0-only
pragma solidity 0.8.26;

import { SigilTestBase } from "./utils/SigilTestBase.sol";
import { IZKMint } from "token/zk_mint/interfaces/IZKMint.sol";
import { IPoseidon2 } from "token/zk_mint/interfaces/IPoseidon2.sol";
import { VmSafe } from "forge-std/Vm.sol";

/**
  @custom:benediction DEVS BENEDICAT ET PROTEGAT CONTRACTVM MEVM
  @title Tests for the ZK mint (ERC-7503) in the Sigil token.
  @author Tim Clancy <tim-clancy.eth>

  These tests use real proofs generated by the Noir circuit and the real
  ZKMintVerifier contract. The on-chain hash tree state is recreated
  through an actual token transfer to the burn address, matching the single-leaf
  tree that existed when the proofs were generated.

  NOTE: All proof fixtures must be regenerated after the circuit migration to
  multi-burn / EIP-712 / two-stage address derivation. Tests are structured for
  the new 67-input public input layout.

  @custom:date February 2026
*/
contract SigilZKMintTest is
  SigilTestBase {

  /// The burn address derived from two-stage blinded address derivation.
  address constant BURN_ADDRESS =
    0xAAaE88C9D59da8724Cd824aF8774c6d3c2f3D690;

  /// The total amount sent to the burn address (total_burned from the proof).
  uint256 constant BURN_AMOUNT = 100 ether;

  /// Decoded public inputs from the self-relay proof fixture.
  uint256 internal amount;
  address internal to;
  IZKMint.RewardData internal rewardData;
  IZKMint.BurnInput[] internal burns;
  uint256 internal fixtureRoot;

  /// The raw self-relay proof bytes.
  bytes internal proof;

  /// Re-declare events so we can use `vm.expectEmit`.
  event ZKMintExecuted (uint256 amount);
  event Nullified (uint256 indexed nullifier, bytes totalMintedEncrypted);

  /// Decode 67 x 32-byte big-endian public inputs into typed values.
  /// Noir serializes [BurnDataPublic; 32] with interleaved struct fields:
  /// [0] amount, [1] sigHash, [2] hash0, [3] null0, [4] hash1, [5] null1,
  /// ..., [64] hash31, [65] null31, [66] root.
  function _decodePublicInputs (
    bytes memory _raw
  ) internal pure returns (
    uint256 amount_,
    uint256[] memory accountNoteHashes_,
    uint256[] memory accountNoteNullifiers_,
    uint256 root_,
    uint256 numActive_
  ) {
    require(_raw.length == 67 * 32, "unexpected public_inputs size");
    assembly {
      amount_ := mload(add(_raw, 0x20))
    }

    accountNoteHashes_ = new uint256[](32);
    accountNoteNullifiers_ = new uint256[](32);

    for (uint256 i = 0; i < 32; i++) {
      // Interleaved pairs starting at field 2: (hash_i, null_i).
      uint256 hashOffset = 0x60 + i * 0x40;
      uint256 nullOffset = 0x80 + i * 0x40;
      uint256 h;
      uint256 n;
      assembly {
        h := mload(add(_raw, hashOffset))
        n := mload(add(_raw, nullOffset))
      }
      accountNoteHashes_[i] = h;
      accountNoteNullifiers_[i] = n;
    }

    assembly {
      root_ := mload(add(_raw, 0x860))
    }

    numActive_ = 0;
    for (uint256 i = 0; i < 32; i++) {
      if (accountNoteHashes_[i] != 0) {
        numActive_ = i + 1;
      } else {
        break;
      }
    }
  }

  /// Build a BurnInput array from decoded public inputs.
  /// @param _newTotalMinted The new total minted for this burn; encoded as the
  ///   `totalMintedEncrypted` field (must match what inputgen used for EIP-712).
  function _buildBurns (
    uint256[] memory _hashes,
    uint256[] memory _nullifiers,
    uint256 _numActive,
    uint256 _newTotalMinted
  ) internal pure returns (IZKMint.BurnInput[] memory burns_) {
    burns_ = new IZKMint.BurnInput[](_numActive);
    for (uint256 i = 0; i < _numActive; i++) {
      burns_[i] = IZKMint.BurnInput({
        accountNoteHash: _hashes[i],
        accountNoteNullifier: _nullifiers[i],
        totalMintedEncrypted: abi.encode(_newTotalMinted)
      });
    }
  }

  /// Set up the test environment.
  function setUp () public {
    _setUpSigil();

    // Transfer to the burn address creates exactly one balance leaf.
    token.transfer(BURN_ADDRESS, BURN_AMOUNT);

    // Load self-relay proof fixture.
    proof = vm.readFileBinary("test/token/data/self_relay_proof");
    bytes memory _raw = vm.readFileBinary(
      "test/token/data/self_relay_public_inputs"
    );

    uint256 _numActive;
    uint256[] memory _hashes;
    uint256[] memory _nullifiers;

    (amount, _hashes, _nullifiers, fixtureRoot, _numActive) =
      _decodePublicInputs(_raw);

    // Build BurnInput array. For the first mint, new_total_minted = amount.
    IZKMint.BurnInput[] memory _burns =
      _buildBurns(_hashes, _nullifiers, _numActive, amount);
    for (uint256 i = 0; i < _burns.length; i++) {
      burns.push(_burns[i]);
    }

    // Build reward data from env or defaults (self-relay).
    to = makeAddr("recipient");
    rewardData = IZKMint.RewardData({
      relayerAddress: address(0),
      priorityFee: 0,
      conversionRate: 0,
      maxReward: 0
    });
  }

  /// Full real-proof self-relay ZK mint.
  function test_zkMint_selfRelay () public {
    assertEq(amount, 50 ether, "fixture amount should be 50 ether");

    assertEq(
      token.root(), fixtureRoot, "tree root mismatch -- regenerate fixtures"
    );
    uint256 _supplyBefore = token.totalSupply();
    uint256 _recipientBefore = token.balanceOf(to);

    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );

    assertEq(token.balanceOf(to), _recipientBefore + amount);
    assertEq(token.totalSupply(), _supplyBefore);
    assertEq(token.nullifiers(burns[0].accountNoteNullifier), amount + 1);
  }

  /// ZKMintExecuted event is emitted with correct values.
  function test_zkMint_emitsEvent () public {
    vm.expectEmit(false, false, false, true, address(token));
    emit ZKMintExecuted(amount);

    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );
  }

  /// Nullified event carries the correct indexed nullifier and TSE data.
  function test_zkMint_emitsNullifiedEvent () public {
    vm.expectEmit(true, false, false, true, address(token));
    emit Nullified(
      burns[0].accountNoteNullifier, burns[0].totalMintedEncrypted
    );

    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );
  }

  /// Replaying the same proof (same nullifier) reverts.
  function test_zkMint_revertNullifierAlreadyExists () public {
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );

    vm.expectRevert(IZKMint.NullifierAlreadyExists.selector);
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );
  }

  /// A fabricated root not in the roots mapping reverts.
  function test_zkMint_revertInvalidRoot () public {
    uint256 _fakeRoot = 42;

    vm.expectRevert(IZKMint.InvalidRoot.selector);
    token.zkMint(
      amount, to, rewardData, burns, _fakeRoot, proof
    );
  }

  /// Flipping a byte in the proof causes a revert.
  function test_zkMint_revertTamperedProof () public {
    bytes memory _tampered = proof;
    _tampered[0] = _tampered[0] ^ 0xff;

    vm.expectRevert();
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, _tampered
    );
  }

  /// All-zero proof bytes cause a revert.
  function test_zkMint_revertZeroProof () public {
    bytes memory _zero = new bytes(proof.length);

    vm.expectRevert();
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, _zero
    );
  }

  /// Empty proof bytes cause a revert.
  function test_zkMint_revertEmptyProof () public {
    bytes memory _empty = new bytes(0);

    vm.expectRevert();
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, _empty
    );
  }

  /// Changing the amount while keeping the original proof reverts.
  /// The UltraHonk verifier reverts with its own error (SumcheckFailed) when
  /// public inputs don't match the proof, so we use a generic expectRevert.
  function test_zkMint_revertTamperedAmount () public {
    vm.expectRevert();
    token.zkMint(
      amount + 1, to, rewardData, burns, fixtureRoot, proof
    );
  }

  /// Changing the recipient while keeping the original proof reverts (EIP-712
  /// signature hash mismatch).
  function test_zkMint_revertTamperedRecipient () public {
    address _wrongRecipient = makeAddr("wrong");

    vm.expectRevert();
    token.zkMint(
      amount, _wrongRecipient, rewardData, burns, fixtureRoot, proof
    );
  }

  /// Changing an account note hash while keeping the original proof reverts.
  function test_zkMint_revertTamperedAccountNoteHash () public {
    IZKMint.BurnInput[] memory _tampered =
      new IZKMint.BurnInput[](burns.length);
    _tampered[0] = IZKMint.BurnInput({
      accountNoteHash: burns[0].accountNoteHash ^ 1,
      accountNoteNullifier: burns[0].accountNoteNullifier,
      totalMintedEncrypted: burns[0].totalMintedEncrypted
    });

    vm.expectRevert();
    token.zkMint(
      amount, to, rewardData, _tampered, fixtureRoot, proof
    );
  }

  /// Changing a nullifier while keeping the original proof reverts.
  function test_zkMint_revertTamperedNullifier () public {
    IZKMint.BurnInput[] memory _tampered =
      new IZKMint.BurnInput[](burns.length);
    _tampered[0] = IZKMint.BurnInput({
      accountNoteHash: burns[0].accountNoteHash,
      accountNoteNullifier: burns[0].accountNoteNullifier ^ 1,
      totalMintedEncrypted: burns[0].totalMintedEncrypted
    });

    vm.expectRevert();
    token.zkMint(
      amount, to, rewardData, _tampered, fixtureRoot, proof
    );
  }

  /// Changing totalMintedEncrypted while keeping the original proof reverts
  /// (EIP-712 signature hash mismatch).
  function test_zkMint_revertWrongTotalMintedEncrypted () public {
    IZKMint.BurnInput[] memory _tampered =
      new IZKMint.BurnInput[](burns.length);
    _tampered[0] = IZKMint.BurnInput({
      accountNoteHash: burns[0].accountNoteHash,
      accountNoteNullifier: burns[0].accountNoteNullifier,
      totalMintedEncrypted: abi.encode(uint256(999 ether))
    });

    vm.expectRevert();
    token.zkMint(
      amount, to, rewardData, _tampered, fixtureRoot, proof
    );
  }

  /// Adding reward data to a self-relay proof reverts (EIP-712 mismatch).
  function test_zkMint_revertTamperedRewardData () public {
    IZKMint.RewardData memory _wrongReward = IZKMint.RewardData({
      relayerAddress: address(1),
      priorityFee: 1e9,
      conversionRate: 1,
      maxReward: 1
    });

    vm.expectRevert();
    token.zkMint(
      amount, to, _wrongReward, burns, fixtureRoot, proof
    );
  }

  /// The tree root updates after a successful ZK mint.
  function test_zkMint_treeUpdated () public {
    uint256 _rootBefore = token.root();

    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );

    uint256 _rootAfter = token.root();
    assertTrue(_rootAfter != _rootBefore, "root should change after transfer");
    assertTrue(token.roots(_rootAfter), "new root should be in roots mapping");
  }

  /// Load and execute a ZK mint from fixture files.
  function _executeFixture (
    string memory _proofPath,
    string memory _inputsPath,
    uint256 _newTotalMinted
  ) internal returns (
    uint256 amount_,
    uint256 nullifier_
  ) {
    bytes memory _proof = vm.readFileBinary(_proofPath);
    bytes memory _raw = vm.readFileBinary(_inputsPath);
    uint256 _numActive;
    uint256[] memory _hashes;
    uint256[] memory _nullifiers;
    uint256 _root;
    (amount_, _hashes, _nullifiers, _root, _numActive) =
      _decodePublicInputs(_raw);

    IZKMint.BurnInput[] memory _burns =
      _buildBurns(_hashes, _nullifiers, _numActive, _newTotalMinted);

    token.zkMint(
      amount_, to, rewardData, _burns, _root, _proof
    );
    return (amount_, _burns[0].accountNoteNullifier);
  }

  /// Second mint: mint the remaining 50 ether from the same burn using a
  /// new proof generated against the post-first-transfer tree.
  function test_zkMint_secondSpend () public {
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );

    uint256 _recipientBefore = token.balanceOf(to);
    uint256 _supplyBefore = token.totalSupply();

    (uint256 _amount2, uint256 _nullifier2) = _executeFixture(
      "test/token/data/second_mint_proof",
      "test/token/data/second_mint_public_inputs",
      100 ether // new_total_minted = 50 (first) + 50 (second)
    );

    assertEq(token.balanceOf(to), _recipientBefore + _amount2);
    assertEq(token.totalSupply(), _supplyBefore);
    assertEq(token.nullifiers(_nullifier2), _amount2 + 1);
    assertTrue(
      burns[0].accountNoteNullifier != _nullifier2,
      "nullifiers must differ between spends"
    );
    assertEq(token.nullifiers(burns[0].accountNoteNullifier), amount + 1);
  }

  // -------------------------------------------------------------------------
  // Tree edge cases
  // -------------------------------------------------------------------------

  event NewLeaf (uint256 leaf);

  function test_transfer_skipsLeafWhenTxOriginIsRecipient () public {
    address _recipient = makeAddr("eoa");
    uint256 _rootBefore = token.root();
    vm.prank(address(this), _recipient);
    token.transfer(_recipient, 1 ether);
    assertEq(
      token.root(), _rootBefore,
      "root should not change when tx.origin == recipient"
    );
  }

  function test_transfer_insertsLeafWhenTxOriginDiffers () public {
    address _recipient = makeAddr("contract");
    uint256 _rootBefore = token.root();
    token.transfer(_recipient, 1 ether);
    assertTrue(
      token.root() != _rootBefore,
      "root should change when tx.origin != recipient"
    );
    assertTrue(
      token.roots(token.root()),
      "new root should be in roots mapping"
    );
  }

  function test_zkMint_emitsTwoNewLeaves () public {
    bytes32 _sig = NewLeaf.selector;

    vm.recordLogs();
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );
    VmSafe.Log[] memory _logs = vm.getRecordedLogs();

    uint256 _expectedBalanceLeaf = IPoseidon2(token.poseidon2()).hash(
      uint256(uint160(to)), token.balanceOf(to), token.TOTAL_BURNED_DOMAIN()
    );

    uint256 _count;
    bool _foundAccountNote;
    bool _foundBalanceLeaf;
    for (uint256 i; i < _logs.length; ++i) {
      if (_logs[i].topics.length > 0 && _logs[i].topics[0] == _sig) {
        uint256 _leaf = abi.decode(_logs[i].data, (uint256));
        if (_leaf == burns[0].accountNoteHash) {
          _foundAccountNote = true;
        } else if (_leaf == _expectedBalanceLeaf) {
          _foundBalanceLeaf = true;
        }
        ++_count;
      }
    }

    assertEq(_count, 2, "should emit exactly 2 NewLeaf events");
    assertTrue(_foundAccountNote, "one NewLeaf should be the account note hash");
    assertTrue(_foundBalanceLeaf, "one NewLeaf should be the balance leaf");
  }

  function test_zkMint_skipsBalanceLeafForEOARecipient () public {
    bytes32 _sig = NewLeaf.selector;

    vm.prank(address(this), to);
    vm.recordLogs();
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );
    VmSafe.Log[] memory _logs = vm.getRecordedLogs();

    uint256 _count;
    for (uint256 i; i < _logs.length; ++i) {
      if (_logs[i].topics.length > 0 && _logs[i].topics[0] == _sig) {
        uint256 _leaf = abi.decode(_logs[i].data, (uint256));
        assertEq(
          _leaf, burns[0].accountNoteHash,
          "only NewLeaf should be the account note hash"
        );
        ++_count;
      }
    }

    assertEq(_count, 1, "should emit exactly 1 NewLeaf event for EOA recipient");
  }

  function test_transfer_duplicateBalanceLeafSkipped () public {
    address _recipient = makeAddr("recipient");

    token.transfer(_recipient, 100 ether);
    vm.prank(_recipient);
    token.transfer(address(this), 50 ether);

    bytes32 _sig = NewLeaf.selector;
    uint256 _balanceLeaf = IPoseidon2(token.poseidon2()).hash(
      uint256(uint160(_recipient)), 100 ether, token.TOTAL_BURNED_DOMAIN()
    );
    vm.recordLogs();
    token.transfer(_recipient, 50 ether);
    VmSafe.Log[] memory _logs = vm.getRecordedLogs();

    for (uint256 i; i < _logs.length; ++i) {
      if (_logs[i].topics.length > 0 && _logs[i].topics[0] == _sig) {
        uint256 _leaf = abi.decode(_logs[i].data, (uint256));
        assertTrue(
          _leaf != _balanceLeaf,
          "duplicate balance leaf should not be re-inserted"
        );
      }
    }

    assertEq(token.balanceOf(_recipient), 100 ether);
  }

  // -------------------------------------------------------------------------
  // Rate limit tests
  // -------------------------------------------------------------------------

  function test_zkMint_rateLimitWithinWindow () public {
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );

    _executeFixture(
      "test/token/data/second_mint_proof",
      "test/token/data/second_mint_public_inputs",
      100 ether
    );

    assertEq(token.rateLimitMintedInPeriod(), 100 ether);
  }

  function test_zkMint_rateLimitExceeded () public {
    uint256 _limit = token.totalSupply() * token.rateLimitSupplyBasisPoints() / 10_000;
    uint256 _nearLimit = _limit - 49 ether;
    vm.store(address(token), bytes32(uint256(9)), bytes32(block.timestamp));
    vm.store(address(token), bytes32(uint256(10)), bytes32(_nearLimit));

    vm.expectRevert(IZKMint.RateLimitExceeded.selector);
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );
  }

  function test_zkMint_rateLimitResetsAfterPeriod () public {
    token.zkMint(
      amount, to, rewardData, burns, fixtureRoot, proof
    );

    vm.warp(block.timestamp + 1 days);

    _executeFixture(
      "test/token/data/second_mint_proof",
      "test/token/data/second_mint_public_inputs",
      100 ether
    );

    assertEq(token.rateLimitMintedInPeriod(), 50 ether);
  }

  function test_zkMint_rateLimitUsesFloor () public view {
    assertEq(token.rateLimitPeriod(), 1 days);
    assertEq(token.rateLimitSupplyBasisPoints(), 100);
    assertEq(token.rateLimitFloor(), 1_000_000e18);
    uint256 _limit = token.totalSupply() * token.rateLimitSupplyBasisPoints() / 10_000;
    assertTrue(
      _limit > token.rateLimitFloor(),
      "1% of supply should exceed the floor at full supply"
    );
  }

  // -------------------------------------------------------------------------
  // Array length validation
  // -------------------------------------------------------------------------

  function test_zkMint_revertEmptyBurns () public {
    IZKMint.BurnInput[] memory _empty =
      new IZKMint.BurnInput[](0);

    vm.expectRevert(IZKMint.InvalidArrayLength.selector);
    token.zkMint(
      amount, to, rewardData, _empty, fixtureRoot, proof
    );
  }

  function test_zkMint_revertTooManyBurns () public {
    IZKMint.BurnInput[] memory _tooMany =
      new IZKMint.BurnInput[](33);

    vm.expectRevert(IZKMint.InvalidArrayLength.selector);
    token.zkMint(
      amount, to, rewardData, _tooMany, fixtureRoot, proof
    );
  }

  function test_zkMint_revertMaxRewardExceedsAmount () public {
    IZKMint.RewardData memory _badReward = IZKMint.RewardData({
      relayerAddress: address(1),
      priorityFee: 0,
      conversionRate: 0,
      maxReward: amount // maxReward >= amount
    });

    vm.expectRevert(IZKMint.MaxRewardExceedsAmount.selector);
    token.zkMint(
      amount, to, _badReward, burns, fixtureRoot, proof
    );
  }
}
