// SPDX-License-Identifier: LicenseRef-VPL WITH AGPL-3.0-only
pragma solidity ^0.8.0;

import { WithSigner } from "./util/WithSigner.sol";
import { IZKMint } from "token/zk_mint/interfaces/IZKMint.sol";
import { Sigil } from "token/Sigil.sol";

/**
  @custom:benediction DEVS BENEDICAT ET PROTEGAT CONTRACTVM MEVM
  @title Submit a ZK mint.
  @author Tim Clancy <tim-clancy.eth>
  @custom:terry "Is this too much voodoo for the next ten centuries?"

  A script to submit a ZK mint to the Sigil token using a proof and
  public inputs generated by `bb`.

  @custom:date February 11th, 2026.
*/
contract ZKMintScript is
  WithSigner {

  /// Run the ZK mint script.
  function run () external withSignerIndex(1) {
    address _token = vm.envAddress("TOKEN_EXPECTED_ADDRESS");
    string memory _proofDir = vm.envOr(
      "PROOF_DIR",
      string("../circuits/target/proof")
    );

    bytes memory _proof = vm.readFileBinary(
      string.concat(_proofDir, "/proof")
    );
    bytes memory _raw = vm.readFileBinary(
      string.concat(_proofDir, "/public_inputs")
    );

    (
      uint256 _amount,
      IZKMint.BurnInput[] memory _burns,
      uint256 _root
    ) = _decodeBurns(_raw);

    _submit(Sigil(_token), _amount, _burns, _root, _proof);
  }

  /// Submit the ZK mint with reward data from environment.
  function _submit (
    Sigil _sigil,
    uint256 _amount,
    IZKMint.BurnInput[] memory _burns,
    uint256 _root,
    bytes memory _proof
  ) private {
    address _to = vm.envAddress("MINT_RECIPIENT");
    IZKMint.RewardData memory _rewardData = IZKMint.RewardData({
      relayerAddress: vm.envOr("RELAYER_ADDRESS", address(0)),
      priorityFee: vm.envOr("PRIORITY_FEE", uint256(0)),
      conversionRate: vm.envOr("CONVERSION_RATE", uint256(0)),
      maxReward: vm.envOr("MAX_REWARD", uint256(0))
    });
    _sigil.zkMint(_amount, _to, _rewardData, _burns, _root, _proof);
  }

  /// Decode public inputs and build the BurnInput array.
  /// Noir uses interleaved layout: [amount, sigHash, hash0, null0, hash1,
  /// null1, ..., hash31, null31, root].
  function _decodeBurns (
    bytes memory _raw
  ) internal pure returns (
    uint256 amount_,
    IZKMint.BurnInput[] memory burns_,
    uint256 root_
  ) {
    require(_raw.length == 67 * 32, "unexpected public_inputs size");
    assembly {
      amount_ := mload(add(_raw, 0x20))
      root_   := mload(add(_raw, 0x860))
    }

    // Count active entries (interleaved: hash at stride 0x40).
    uint256 _numActive;
    for (uint256 i = 0; i < 32; i++) {
      uint256 h;
      assembly { h := mload(add(_raw, add(0x60, mul(i, 0x40)))) }
      if (h != 0) { _numActive = i + 1; } else { break; }
    }

    burns_ = new IZKMint.BurnInput[](_numActive);
    for (uint256 i = 0; i < _numActive; i++) {
      uint256 h;
      uint256 n;
      assembly {
        h := mload(add(_raw, add(0x60, mul(i, 0x40))))
        n := mload(add(_raw, add(0x80, mul(i, 0x40))))
      }
      burns_[i] = IZKMint.BurnInput({
        accountNoteHash: h,
        accountNoteNullifier: n,
        totalMintedEncrypted: new bytes(32)
      });
    }
  }
}
